export type User = {
    id: string;
    image: string;
    userTier: number;
    bankAccount: number;
    bank: string;
    phoneNumber: string;
    userEmail: string;
    bvn: number;
    gender: string; 
    maritalStatus: "married" | "single" | "divorced";
    children: "None" | "1" | "2" | "3" | "4";
    residence: "Bungalow" | "Flat" | "Parent's Apartment";
    levelOfEducation: "B.sc" | "M.sc" | "B.Tech" | "B.Eng";
    employmentStatus: "Employed" | "UnEmployed";
    sectorOfEmployment: "Fintech" | "Engineering" | "Banking";
    durationOfEmployment: string; 
    officeEmail: string;
    monthlyIncome: string; 
    monthlyIncomeRange: string; 
    loanRepayment: string; 
    twitter: string;
    facebook: string;
    instagram: string;
    guarantorFullName: string;
    guarantorPhoneNumber: string;
    guarantorEmailAddress: string;
    status: "Inactive" | "Active" | "Pending" | "Blacklisted";
    username: string;
    organisation: "Lendsqr";
    dateJoined: string; 
    guarantorRelationship: "Sister" | "Brother" | "Uncle" | "Father" | "Mother" | "Aunty";
};
